export const registryAbi = [
  { type: "constructor", inputs: [{ name: "_uAuthContract", type: "address", internalType: "address" }], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "addNewContract",
    inputs: [
      { name: "_id", type: "bytes4", internalType: "bytes4" },
      { name: "_contractAddr", type: "address", internalType: "address" },
      { name: "_waitPeriod", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addNewThirdPartyContract",
    inputs: [{ name: "_contractAddr", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }],
    stateMutability: "nonpayable",
  },
  { type: "function", name: "approveContractChange", inputs: [{ name: "_id", type: "bytes4", internalType: "bytes4" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "approveWaitPeriodChange", inputs: [{ name: "_id", type: "bytes4", internalType: "bytes4" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "cancelContractChange", inputs: [{ name: "_id", type: "bytes4", internalType: "bytes4" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "cancelWaitPeriodChange", inputs: [{ name: "_id", type: "bytes4", internalType: "bytes4" }], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "entries",
    inputs: [{ name: "", type: "bytes4", internalType: "bytes4" }],
    outputs: [
      { name: "contractAddr", type: "address", internalType: "address" },
      { name: "waitPeriod", type: "uint256", internalType: "uint256" },
      { name: "changeStartTime", type: "uint256", internalType: "uint256" },
      { name: "inContractChange", type: "bool", internalType: "bool" },
      { name: "inWaitPeriodChange", type: "bool", internalType: "bool" },
      { name: "exists", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  { type: "function", name: "getAddr", inputs: [{ name: "_id", type: "bytes4", internalType: "bytes4" }], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "isRegistered", inputs: [{ name: "_id", type: "bytes4", internalType: "bytes4" }], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "view" },
  { type: "function", name: "isVerifiedContract", inputs: [{ name: "_addr", type: "address", internalType: "address" }], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "view" },
  { type: "function", name: "isVerifiedContract", inputs: [{ name: "_id", type: "bytes4", internalType: "bytes4" }], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "view" },
  { type: "function", name: "owner", inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "pendingAddresses", inputs: [{ name: "", type: "bytes4", internalType: "bytes4" }], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "pendingWaitTimes", inputs: [{ name: "", type: "bytes4", internalType: "bytes4" }], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "previousAddresses", inputs: [{ name: "", type: "bytes4", internalType: "bytes4" }], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "revertToPreviousAddress", inputs: [{ name: "_id", type: "bytes4", internalType: "bytes4" }], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "startContractChange",
    inputs: [
      { name: "_id", type: "bytes4", internalType: "bytes4" },
      { name: "_newContractAddr", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "startWaitPeriodChange",
    inputs: [
      { name: "_id", type: "bytes4", internalType: "bytes4" },
      { name: "_newWaitPeriod", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "thirdPartyEntries",
    inputs: [{ name: "", type: "bytes4", internalType: "bytes4" }],
    outputs: [
      { name: "contractAddr", type: "address", internalType: "address" },
      { name: "exists", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  { type: "function", name: "verifiedContracts", inputs: [{ name: "", type: "address", internalType: "address" }], outputs: [{ name: "", type: "bool", internalType: "bool" }], stateMutability: "view" },
  {
    type: "event",
    name: "AddNewContract",
    inputs: [
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "bytes4", indexed: false, internalType: "bytes4" },
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AddNewThirdPartyContract",
    inputs: [
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "bytes4", indexed: false, internalType: "bytes4" },
      { name: "", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ApproveContractChange",
    inputs: [
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "bytes4", indexed: false, internalType: "bytes4" },
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ApproveWaitPeriodChange",
    inputs: [
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "bytes4", indexed: false, internalType: "bytes4" },
      { name: "", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CancelContractChange",
    inputs: [
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "bytes4", indexed: false, internalType: "bytes4" },
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CancelWaitPeriodChange",
    inputs: [
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "bytes4", indexed: false, internalType: "bytes4" },
      { name: "", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EditThirdPartyContract",
    inputs: [
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "bytes4", indexed: false, internalType: "bytes4" },
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RevertToPreviousAddress",
    inputs: [
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "bytes4", indexed: false, internalType: "bytes4" },
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StartContractChange",
    inputs: [
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "bytes4", indexed: false, internalType: "bytes4" },
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StartWaitPeriodChange",
    inputs: [
      { name: "", type: "address", indexed: false, internalType: "address" },
      { name: "", type: "bytes4", indexed: false, internalType: "bytes4" },
      { name: "", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadyInContractChangeError", inputs: [{ name: "", type: "bytes4", internalType: "bytes4" }] },
  { type: "error", name: "AlreadyInWaitPeriodChangeError", inputs: [{ name: "", type: "bytes4", internalType: "bytes4" }] },
  {
    type: "error",
    name: "ChangeNotReadyError",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "EmptyPrevAddrError", inputs: [{ name: "", type: "bytes4", internalType: "bytes4" }] },
  { type: "error", name: "EntryAlreadyExistsError", inputs: [{ name: "", type: "bytes4", internalType: "bytes4" }] },
  { type: "error", name: "EntryNonExistentError", inputs: [{ name: "", type: "bytes4", internalType: "bytes4" }] },
  { type: "error", name: "EntryNotInChangeError", inputs: [{ name: "", type: "bytes4", internalType: "bytes4" }] },
];
